### ISSUE TITLE
check English text team description

### ISSUE THREAD

**Issue by IlyaTarutov** [DaoCasino/MainSite#17]
/Users/ilyatarutov/Desktop/Снимок экрана 2017-01-24 в 17.38.17.png

**Comment by KsenyaSerova** [comment]
same issue as in https://github.com/DaoCasino/MainSite/issues/13 - мне нужна информация от @noxonsu 

- [ ] с подключением thompson reuters" - непонятно как что к чему подключается - data feed из Thompson, some API?
- [ ] стоит ли упоминать fl.ru ? - по моему они известны только русскоязычной аудитории
- [ ] "активный участник open source сообщества" - либо ссылки на конкретные репозитории (активное участие), либо изменить на "считает что open source это самый правильный путь разработки софта" (мнение)
- [ ] 3000 users бота тоже можно не писать. Для нишевой аудитории это много и хорошо, но для не нишевой это мало - те кто не врубается в то что аудитория нишевая не врубятся.
- [ ] добавить какие знает языки программирования, какие frameworks - какими пользуется регулярно
- [ ]  добавить опыт работы в команде, с командой, особенно в качестве project lead. Роль CTO это предполагает

**Comment by noxonsu** [comment]
1 да data feed, а именно Elektron Real Time Data
2 удаляем
3 меняем на мнение
4 убираем
5 js, php - эти регулярно, фреймворки: node.js, angular.js, electron.js
6 https://themeforest.net/item/mycity-geolocation-directory-and-events-guide/12265153 роль team lead в команде 5ть человек (1 бекенд, 2 фронтендера, 1 дизайнер, тестер, я)
